defaults:
  - dataset: my_libri
  - hider: rnn
  - finder: rnn
  - combiner: rnn

use_f0: False

training_finder:
  batch_size: 128
  lr: 0.001

training:
  batch_size: 64
  lr_find: False
  wandb: False
  clip: 0.5
  #lr: 0.007
  #lr: 0.10964781961431852
  lr_g: 0.001
  lr_f: 0.0001

control_variables: 
  f0_bins: 100
  f0_min: 60
  f0_max: 400
  speaker_embedding_dim: 512

# For hifigan mels
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_length: 256
win_length: 1024
sr: 22050

fmin: 0
fmax: 8000

model:
  hidden_size: 80
  beta: 600.