defaults:
  - dataset: my_libri
  - hider: rnn
  - finder: rnn
  - combiner: rnn
  #- override hydra/launcher: submitit_local
  - override hydra/sweeper: optuna

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: lr_g_sweep
    n_trials: 12
    storage: sqlite:///optuna.db #https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#distributed
    n_jobs: 12
    params:
      training.lr_g: range(0.00000001, 0.0005)
      training.epochs: 1
      training.metric: 'combiner_loss'
      

#  launcher:
#    timeout_min: 240
#    cpus_per_gpu: 8
#    gpus_per_task: 1
#    mem_gb: 16
#    array_parallelism: 12
#    tasks_per_node: 5
#    #nodes: 1


use_f0: True

training_finder:
  batch_size: 128
  lr: 0.001

training:
  epochs: 1000
  log_n_audios: 1
  batch_size: 64
  lr_find: False
  wandb: False
  clip: 0.5
  #lr: 0.007
  #lr: 0.10964781961431852
  lr_g: 0.0005
  lr_f: 0.0001
  val_check_interval: 10 # in epochs
  metric: 'combiner_loss'
  adversarial_start: 10000
  scheduler_step: 500


control_variables: 
  f0_bins: 100
  f0_min: 60
  f0_max: 400
  speaker_embedding_dim: 512

# For hifigan mels
num_mels: 80
num_freq: 1025
n_fft: 1024
hop_length: 256
win_length: 1024
sr: 22050

fmin: 0
fmax: 8000

model:
  hidden_size: 80
  beta: 600.
