root: ~/datasets
subset: train-clean-100
save_as: LibriTTS
#validation_split: 0.005
valid_size: 300
rsync: False
download: True
valid_json: preprocessed_data/LibriTTS/valid.json
train_json: preprocessed_data/LibriTTS/train.json
test_json: preprocessed_data/LibriTTS/test.json